### ISSUE TITLE
Autocomplete options prop default

### ISSUE THREAD

**Issue by aaronhayes** [lookfirst/mui-rff#122]
**Describe the bug**
`Autocomplete`  will error when `options` is `undefined`. We should make the default `[]`. This is how [material-ui](https://material-ui.com/api/autocomplete/) handle it.

**To Reproduce**
Set `options` on `Autocomplete` component to undefined.

**Expected behavior**
Expect an empty options list instead of an error.

**Versions**
Happening since `>=1.8.0`. Works fine on `1.7.3` 

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Any
 - Version: Any

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Any
 - Browser Any
 - Version Any

**Additional context**
```
AutocompleteWrapper
src/Autocomplete.tsx:78
  75 | // yuck...
  76 | let defaultValue: any = undefined;
  77 | if (value !== undefined && value !== null) {
> 78 | 	options.forEach((option: any) => {
     | ^  79 | 		const optionValue = getOptionValue(option);
  80 | 		if (multiple) {
  81 | 			if (!defaultValue) defaultValue = [];
```

**Comment by aaronhayes** [comment]
Almost exactly the same problem occurs with `value` when `multiple` is `true`

```
TypeError: value.forEach is not a function
(anonymous function)
src/Autocomplete.tsx:82
  79 | const optionValue = getOptionValue(option);
  80 | if (multiple) {
  81 | 	if (!defaultValue) defaultValue = [];
> 82 | 	(value as any).forEach((v: any) => {
     | ^  83 | 		if (v === optionValue) {
  84 | 			defaultValue.push(option);
  85 | 		}

```

**Comment by lookfirst** [comment]
Hmm... options is defined as `options: AutocompleteData[];` in the interface. Not sure I see the benefit except for poor JS folks, at which point I'm kind of 🤷‍♂ since JS is missing types on well... everything.

![image](https://user-images.githubusercontent.com/85355/74303974-72db1f80-4d10-11ea-94c7-fd8528a00c58.png)

**Comment by aaronhayes** [comment]
That's fair. I think the benefit is mostly just following the material ui standards as closely as possible, so people don't get caught out by slight differences.

I actually think the bigger issue is my follow up comment https://github.com/lookfirst/mui-rff/issues/122#issuecomment-585028175

**Comment by aaronhayes** [comment]
We should just add a simple check to `value` before calling `forEach` incase it is undefined.

**Comment by lookfirst** [comment]
> We should just add a simple check to `value` before calling `forEach` incase it is undefined.

That's why [I added documentation](https://github.com/lookfirst/mui-rff/commit/2c74e9fb1586e6e981d882c348d4f5b8b59dac7f#diff-04c6e90faac2675aa89e2176d2eec7d8R276) earlier today.

**Comment by lookfirst** [comment]
I'm going to close this for now. Happy to keep discussing as always! 

I'm kind of prone right now to seeing how often it comes up before I start adding defensive programming everywhere. I kind of like that it just errors out because additional code just penalizes bytes.

This is the second time today it has come up, but let's see if the documentation helps (you are unfortunately an old hat so probably didn't see that documentation change heh).

**Comment by lookfirst** [comment]
@see #120

**Comment by aaronhayes** [comment]
haha didn't see that 👍

**Comment by aaronhayes** [comment]
Turns out options is now required in material-ui now https://github.com/mui-org/material-ui/pull/19648 so even less reason to change!

**Comment by lookfirst** [comment]
@aaronhayes Yea, I've learned over the years that having stuff default to empty list (or empty object) instead of say null/undefined is far better/easier because it means that you don't have to null/undefined check everything in code.
